version: '3.7'
services: 
    cassandra:
        build: 
            context: cassandra
        image: dotingestion2:cassandra
        container_name: cassandra
        environment: 
            - CASSANDRA_BROADCAST_ADDRESS=cassandra
            - CASSANDRA_KEYSPACE=dota_ks
            - CASSANDRA_MATCH_TABLE=matches
        ports: 
            - "9042:9042"

    zookeeper:
        image: confluentinc/cp-zookeeper:6.1.1
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_SERVER_ID: "1"

    kafkaserver:
        image: confluentinc/cp-kafka:6.1.1
        container_name: kafkaserver
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
        environment:
          KAFKA_BROKER_ID: 0
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaserver:9092
          KAFKA_MESSAGE_MAX_BYTES: 1677722
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_DEFAULT_REPLICATION_FACTOR: 1
          KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 1

    kafkaworker1:
        image: confluentinc/cp-kafka:6.1.1
        container_name: kafkaworker1
        depends_on:
          - kafkaserver
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaworker1:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
          KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 2
          KAFKA_DEFAULT_REPLICATION_FACTOR: 2
          KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 2

    connect-cassandra:
        build: 
            context: connect-cassandra
        image: dotingestion2:kafka-connect-cassandra
        container_name: connect-cassandra
        depends_on:
          - kafkaserver
          - cassandra

    connect-elasticsearch:
        build: 
            context: connect-elastic
        image: dotingestion2:kafka-connect-elasticsearch
        container_name: connect-elasticsearch
        depends_on:
          - kafkaserver
          - elasticsearch

    kafkastream:
        build: 
            context: stream
        image: dotingestion2:kafkastream
        container_name: kafkastream
        depends_on: 
            - kafkaserver
            - kadkaproducer

    kafkaproducer:
        build: 
            context: ingestion
        image: dotingestion2:ingestion
        container_name: kafkaproducer
        depends_on: 
            - kafkaserver

    webui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafkaWebUI
        environment:
            KAFKA_CLUSTERS_0_NAME: my_cluster
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafkaServer:9092
        ports: 
            - 8080:8080
        depends_on: 
            - kafkaserver

    spark:
        build: 
            context: spark
        image: dotingestion2:spark
        container_name: spark
        depends_on: 
            - kafkaserver
            - elasticsearch
            - connect-elasticsearch

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        container_name: elasticsearch
        ports:
            - "9200:9200"
        environment:
            - node.name=elasticsearch
            - cluster.name=elasticsearch-docker-cluster
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        depends_on: 
            - kafkaserver
        
    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.1
        container_name: kibana
        ports:
            - "5601:5601"
        depends_on: 
            - kafkaserver
