apiVersion: v1
kind: Service
metadata:
  labels:
    service: cassandra
  name: cassandra
spec:
  type: NodePort
  ports:
    - name: "9042"
      port: 9042
      targetPort: 9042
      nodePort: 30001
  selector:
    service: cassandra
