apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafkaserver
  name: kafkaserver
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    service: kafkaserver
status:
  loadBalancer: {}
