apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafkaproducer
  name: kafkaproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafkaproducer
  strategy: {}
  template:
    metadata:
      labels:
        service: kafkaproducer
    spec:
      containers:
        - env:
            - name: INTERVAL
              value: "40"
            - name: API_ENDPOINT
              value: http://api.steampowered.com/IDOTA2Match_570/GetMatchHistoryBySequenceNum/V001/?key={}&start_at_match_seq_num={}
            - name: TOPIC
              value: dota_raw
            - name: MATCH_SEQ_NUM
              value: steam
            - name: HISTORY_ENDPOINT
              value: https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001/?key={}&matches_requested=1
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key
                  key: key
          image: tendto/dotingestion2:ingestion
          name: kafkaproducer
          imagePullPolicy: Always
          resources: {}
      restartPolicy: Always
status: {}
