apiVersion: v1
kind: Service
metadata:
  labels:
    service: webui
  name: webui
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    service: webui
